
Training instances classifier
Traceback (most recent call last):
  File "/Users/filip/thesis/Classifier.py", line 310, in <module>
    fire.Fire(handler)
  File "/Users/filip/opt/anaconda3/lib/python3.9/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/Users/filip/opt/anaconda3/lib/python3.9/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/Users/filip/opt/anaconda3/lib/python3.9/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/Users/filip/thesis/Classifier.py", line 293, in handler
    trainInstancesClassifier()
  File "/Users/filip/thesis/Classifier.py", line 157, in trainInstancesClassifier
    outputs = net(inputs)
  File "/Users/filip/opt/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/filip/thesis/Classifier.py", line 123, in forward
    x = self.self_attention(x)
  File "/Users/filip/opt/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/filip/thesis/Classifier.py", line 93, in forward
    dot = F.softmax(dot, dim = 3)
  File "/Users/filip/opt/anaconda3/lib/python3.9/site-packages/torch/nn/functional.py", line 1680, in softmax
    ret = input.softmax(dim)
IndexError: Dimension out of range (expected to be in range of [-3, 2], but got 3)